version: '3.1'

services:

  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234321  # Set your root password here
      MYSQL_DATABASE: iocl
    ports:
      - "3307:3306"  # Map local port 3307 to container port 3306
