version: '3.1'

services:

  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: ""
      DB_NAME: iocl
      DB_PORT: 3307
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: iocl
    ports:
      - "3307:3306"  # Maps port 3307 on the host to port 3306 on the container

      - "3307:3306"  # Map local port 3307 to container port 3306
