version: '3.1'

services:

  web:
    image: php:8.1-apache
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: iocl
    ports:
      - "3306:3306"
